defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:12

commands:
  runtests:
    description: "Checkout, install dependencies, and run tests"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Run tests
          command: npm t

version: 2.1
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  testnode6:
    <<: *defaults
    docker:
      - image: circleci/node:6.11.5
    steps:
      - runtests
  testnode8:
    <<: *defaults
    docker:
      - image: circleci/node:8
    steps:
      - runtests
  testnode10:
    <<: *defaults
    docker:
      - image: circleci/node:10
    steps:
      - runtests
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm t
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Check syntax
          command: npm run lint -- --plugin log
  publish:
    <<: *defaults
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Set NPM tokens
          command: echo -e $NPMRC > ~/.npmrc
      - run:
          name: Publish to NPM
          command: npx published
  glossary:
    <<: *defaults
    steps:
      - run:
          name: Add to Glossary
          command: |
            curl --user ${CIRCLECI_API_TOKEN}: \
              --header "Content-Type: application/json" \
              --data "{\"build_parameters\":{\"TRIGGERING_REPOSITORY\":\"${CIRCLE_REPOSITORY_URL}\"}}" \
              --request POST \
              https://circleci.com/api/v1.1/project/github/fiverr/glossary/tree/master

workflows:
  version: 2.1
  ci-cd:
    jobs:
      - install
      - test:
          requires:
            - install
      - lint:
          requires:
            - install
      - testnode6
      - testnode8
      - testnode10
      - publish:
          context: org-global
          requires:
            - test
            - lint
            - testnode6
            - testnode8
            - testnode10
      - glossary:
          context: org-global
          requires:
            - publish
          filters:
            branches:
              only:
                - master
