defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cimg/node:lts
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
version: 2.1
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - persist_to_workspace:
          root: .
          paths:
            - ./node_modules

  test:
    parameters:
      image:
        description: docker image
        default: cimg/node:lts
        type: string
    working_directory: ~/app
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Run tests
          command: npm t
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Check syntax
          command: npm run lint -- --plugin log
  publish:
    <<: *defaults
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Set NPM tokens
          command: echo -e $NPMRC > ~/.npmrc
      - run:
          name: Publish to NPM
          command: npx published
  glossary:
    <<: *defaults
    steps:
      - run:
          name: Add to Glossary
          command: |
            curl --user ${CIRCLECI_API_TOKEN}: \
              --header "Content-Type: application/json" \
              --data "{\"build_parameters\":{\"TRIGGERING_REPOSITORY\":\"${CIRCLE_REPOSITORY_URL}\"}}" \
              --request POST \
              https://circleci.com/api/v1.1/project/github/fiverr/glossary/tree/master

workflows:
  version: 2.1
  ci-cd:
    jobs:
      - install
      - test:
          requires:
            - install
          matrix:
            parameters:
              image:
                - cimg/node:10.25
                - cimg/node:12.22
                - cimg/node:14.18
                - cimg/node:16.15
                - cimg/node:18.0
      - lint:
          requires:
            - install
            - test
      - publish:
          context: org-global
          requires:
            - test
            - lint
            - test
      - glossary:
          context: org-global
          requires:
            - publish
          filters:
            branches:
              only:
                - master
