defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cimg/node:18.17
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS

version: 2.1
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - ./node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm t
      - run: npm run lint -- --plugin log
  compatibility:
    parameters:
      image:
        description: "node version"
        default: "lts"
        type: string
    <<: *defaults
    docker:
      - image: "cimg/node:<<parameters.image>>"
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - run: npm i
      - run: npm t
  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Set NPM tokens
          command: echo -e $NPMRC > ~/.npmrc
      - run:
          name: Publish to NPM
          command: npx published
  glossary:
    <<: *defaults
    steps:
      - run:
          name: Add to Glossary
          command: |
            curl --user ${CIRCLECI_API_TOKEN}: \
              --header "Content-Type: application/json" \
              --data "{\"build_parameters\":{\"TRIGGERING_REPOSITORY\":\"${CIRCLE_REPOSITORY_URL}\"}}" \
              --request POST \
              https://circleci.com/api/v1.1/project/github/fiverr/glossary/tree/master

workflows:
  version: 2.1
  ci-cd:
    jobs:
      - install:
          context: org-global
      - compatibility:
          context: org-global
          matrix:
            parameters:
              image:
                - "14.21"
                - "16.20"
                # - "18.17" // default image
                - "20.5"
      - test:
          context: org-global
          requires:
            - install
      - publish:
          context: org-global
          requires:
            - test
            - compatibility
      - glossary:
          context: org-global
          requires:
            - publish
          filters:
            branches:
              only:
                - master
